*** Test Cases ***
Executar Todos Os Testes
    Log    Executando suite completa de testes...

Executar Testes Autenticacao
    Log    Executando testes de autenticação...

Executar Testes Pet
    Log    Executando testes de pet...

Executar Testes Tutor
    Log    Executando testes de tutor...

Executar Testes Estadia
    Log    Executando testes de estadia...